---
language: python
cache: pip
python: "2.7"

# Use a full VM (rather than a sudo-less container), as we need sudo access to
# test this Ansible role.
sudo: true

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install Ansible and other required Python libraries.
  - pip install -r tests/requirements.txt

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml --inventory-file=tests/inventory --syntax-check

  # Run the role/playbook.
  - ansible-playbook tests/test.yml --inventory-file=tests/inventory --connection=local

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook tests/test.yml --inventory-file=tests/inventory --connection=local --skip-tags "test"
    | tee /dev/tty
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

